experiment: style_cls

dataset:
  train: /app/data/cls_dataset/train.csv
  val: /app/data/cls_dataset/val.csv
  test: /app/data/cls_dataset/test.csv

model:
  name: cointegrated/rubert-tiny2
  max_len: 128
  num_labels: 2
  classifier_dropout: 0.1

num_workers: 6
mlflow_tracking_uri: http://localhost:5000

training:
  warmup_steps: 500
  learning_rate: !!float 1e-5
  eval_strategy: epoch
  save_strategy: epoch
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  bf16: true
  bf16_full_eval: true
  num_train_epochs: 5
  torch_compile: True
  optim: adamw_torch_fused
  logging_strategy: steps
  logging_steps: 200
  metric_for_best_model: f1
  report_to: mlflow
  load_best_model_at_end: true
